modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
#issueTrackerURL="https://github.com/Insane96/InsaneLib"

[[mods]]
modId="insanelib"
version="${file.jarVersion}"
displayName="InsaneLib"
displayURL="https://www.curseforge.com/minecraft/mc-mods/insanelib"
#logoFile="examplemod.png"
#credits=""
authors="Insane96MCP"
description='''
A Library mod used by Insane's Mods
'''

[[dependencies.insanelib]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.insanelib]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
