modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Insane96/InsaneLib/issues"

[[mods]]
modId="insanelib"
version="${file.jarVersion}"
displayName="InsaneLib"
displayURL="https://www.curseforge.com/minecraft/mc-mods/insanelib"
#logoFile="examplemod.png"
#credits=""
authors="Insane96MCP"
description='''
A Library mod used by Insane's Mods
'''

[[dependencies.insanelib]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.insanelib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
