modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Insane96/InsaneLib/issues"

[[mods]]
modId="insanelib"
version="${file.jarVersion}"
displayName="InsaneLib"
displayURL="https://www.curseforge.com/minecraft/mc-mods/insanelib"
#logoFile="examplemod.png"
#credits=""
authors="Insane96MCP"
description='''
A Library mod used by Insane's Mods (Progressive Bosses, IguanaTweaks Reborn, Survival Reimagined, and more)
'''

[[dependencies.insanelib]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.insanelib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
