modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Insane96/InsaneLib/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/insanelib"
#logoFile="examplemod.png"
authors="Insane96MCP"
description='''
A Library mod for common code used by Insane's Mods. Also contains a few features for players
'''

[[mixins]]
config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

